version: "3.9"

services:
  autocomplete:
    build: ./services/autocomplete
    ports:
      - "8000:8000"

  asr:
    build: ./services/asr
    ports:
      - "8001:8000"

  speaker:
    build: ./services/speaker
    ports:
      - "8002:8000"

  chatbot:
    build: ./services/chatbot
    ports:
      - "8003:8000"

  tts:
    build: ./services/tts
    ports:
      - "8004:8000"

  etl:
    build: ./services/etl
    ports:
      - "8005:8000"

